# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=110)),
                ('apellidos', models.CharField(blank=True, max_length=110)),
                ('direccion', models.CharField(blank=True, max_length=110)),
                ('edad', models.CharField(blank=True, max_length=110)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=110)),
                ('profesor', models.CharField(blank=True, max_length=110)),
                ('identificacion', models.CharField(blank=True, max_length=110)),
            ],
        ),
    ]
